; ─── MazeBot — PlatformIO configuration ───────────────────────────────────────
[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

; Upload speed (reduce to 460800 if you get flashing errors)
upload_speed = 921600
; Dependencies
lib_deps =adafruit/Adafruit_VL53L0X @ ^1.2.4
build_src_filter = +<*> -<test.cpp>

[env:test]
platform  = espressif32
board     = esp32dev
framework = arduino
lib_deps =adafruit/Adafruit_VL53L0X @ ^1.2.4

build_src_filter = +<test.cpp> -<main_*>
